name: Unit Tests 

on:
  workflow_dispatch:
  push:
     branches:
       - mi-rama
  pull_request:
    types: [opened, synchronize, reopened]
      
jobs:
  sonarcloud:
    name: sonarcloud
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0         
      - name: Install dependencies
        run: npm install
      - name: npm ci
        run: npm ci 
      - name: tests
        run: npm test
      - name: Test and coverage
        run: npm run cover
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONARCLOUD_TOKEN }}